apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-env-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
  LAPINOU_URI: {{ .Values.dependencies.lapinou.uri }}
  MONGODB_URI: {{ .Values.dependencies.database.uri }}