name: Deploy - Prod

on:
  workflow_call:
      
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: CESI-Eats/Payment_DEPLOY

      - name: Helm Upgrade
        run: |
          helm upgrade payment-api-chart ./ -f ./values.yaml --install --namespace cesi-eats --create-namespace